### ISSUE TITLE
adept_loan_mgt is missing

### ISSUE THREAD

**Issue by cchristofr** [bcliang/docker-libgourou#13]
Hello

adept_loan_mgt isn't created when you build the docker file.

**Comment by greboreda** [comment]
Same here! Thankss

**Comment by bcliang** [comment]
Thanks for the report.  I wasn't copying the compiled binary in to the container.

**Comment by bcliang** [comment]
Should use the ubuntu image for now.

**Comment by cchristofr** [comment]
It is fixed. 
Many thanks
