### ISSUE TITLE
[0x500b] Error Couldn't resolve host name

### ISSUE THREAD

**Issue by jonas-lauber** [bcliang/docker-libgourou#8]
Hi,
Your project looks very promising and I would love to use it, but I am having troubles.
I tried to run an interactive terminal and run adept_activate with a valid username/password, but I get 

> Exception code : 0x500b
> Message        : Error Couldn't resolve host name

Do you know what could be the problem ?

**Comment by bcliang** [comment]
Did you build the image yourself or pull from dockerhub? If you built it without issue I'm not sure what could be going on as that means there aren't any network issues (the image is built on official `ubuntu/jammy` and clones code from the repository at `git://soutade.fr/libgourou.git` as part of the build process). 

If you pulled the image from dockerhub it's possible there is a problem with the docker network / network bridge. Some suggestions here:
https://serverfault.com/questions/642981/docker-containers-cant-resolve-dns-on-ubuntu-14-04-desktop-host

From the interactive terminal, you could try to connect to the Adobe activate server to see if DNS is blocked/misconfigured:
```bash
root@...:/home/libgourou# wget -o testnetwork http://adeactivate.adobe.com/adept
--2022-10-30 19:57:08--  http://adeactivate.adobe.com/adept
Resolving adeactivate.adobe.com (adeactivate.adobe.com)... 192.147.130.145
Connecting to adeactivate.adobe.com (adeactivate.adobe.com)|192.147.130.145|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://adeactivate.adobe.com/adept/ [following]
--2022-10-30 19:57:09--  http://adeactivate.adobe.com/adept/
Reusing existing connection to adeactivate.adobe.com:80.
HTTP request sent, awaiting response... 200 OK
Length: 149 [text/html]
Saving to: 'testnetwork'

testnetwork                         100%[=================================================>]     149  --.-KB/s    in 0s      

2022-10-30 19:57:09 (16.6 MB/s) - 'testnetwork' saved [149/149]
```

**Comment by jonas-lauber** [comment]
Hi @bcliang,

I pulled the image from Dockerhub.

I didn't know exactly which URL was called, but I had already tried to do an HTTP call to check the connectivity and DNS lookup.

But I tried again with http://adeactivate.adobe.com/adept, which is working fine too. However I still get the same error.
Here is a dump of my terminal:

```
MacBook-Pro:~$ docker run -v tmp:/home/libgourou/.adept -v tmp:/home/libgourou/files -it --entrypoint /bin/bash bcliang/docker-libgourou
root@bbf8082fc18b:/home/libgourou# wget --verbose http://adeactivate.adobe.com/adept
--2022-10-31 13:43:11--  http://adeactivate.adobe.com/adept
Resolving adeactivate.adobe.com (adeactivate.adobe.com)... 192.147.130.145
Connecting to adeactivate.adobe.com (adeactivate.adobe.com)|192.147.130.145|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://adeactivate.adobe.com/adept/ [following]
--2022-10-31 13:43:12--  http://adeactivate.adobe.com/adept/
Reusing existing connection to adeactivate.adobe.com:80.
HTTP request sent, awaiting response... 200 OK
Length: 149 [text/html]
Saving to: 'adept'

adept                  100%[============================>]     149  --.-KB/s    in 0s      

2022-10-31 13:43:12 (633 KB/s) - 'adept' saved [149/149]

root@bbf8082fc18b:/home/libgourou# adept_activate -u xxxxxxx@gmail.com
!! Warning !! : /home/libgourou/./.adept already exists.
All your data will be overwrite. Would you like to continue ? [y/N] y
Enter password for <xxxxxxx@gmail.com> : 
Exception code : 0x500b
Message        : Error Couldn't resolve host name

root@bbf8082fc18b:/home/libgourou# 
```

So you mean when you pull the latest image from dockerhub and run it is working for you ? So this is really a problem with my setup ?

**Comment by bcliang** [comment]
Sorry for the delay. Yes, I don't have issues on my end.
```
docker run -v /home/brad/repos/docker-libgourou/adobe/:/home/libgourou/.adept -v $(pwd):/home/libgourou/files -it --entrypoint /bin/bash bcliang/docker-libgourou
root@5ea5d1ab8f0c:/home/libgourou# ls
dedrm.sh  entrypoint.sh  files
root@***:/home/libgourou# adept_activate -u ***@gmail.com
!! Warning !! : /home/libgourou/./.adept already exists.
All your data will be overwrite. Would you like to continue ? [y/N] y
Enter password for <***@gmail.com> : 
***@gmail.com fully signed and device activated in /home/libgourou/./.adept
```

**Comment by bcliang** [comment]
Closing for staleness. I was unable to replicate the issue on a borrowed macbook. @jonas-lauber please reopen if there are updates.
